name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: melodic, ROS_REPO: main, CODE_COVERAGE: coveralls.io, COVERALLS_REPO_TOKEN: vKsSLGY58LkaZXEwEjZfkdTtIMWOIkcKW}
          - {ROS_DISTRO: melodic, ROS_REPO: main, CODE_COVERAGE: codecov.io}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'Briancbn/industrial_ci@pr-coverage-rebased'
        env: ${{matrix.env}}
